<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MultiTenantApi.Application\MultiTenantApi.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.1.1" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Honeycomb.OpenTelemetry" Version="1.5.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
